URLS_FOLDER_PATH = "urls"
TASKS_COUNT = 100  # Кол-во заданий, которое будет выполнено за одну сессию
TRIES_COUNT = 2  # Кол-во попыток получить задание
DEFAULT_RETRIES = 2  # Кол-во попыток достучаться до сайта
BOT_ADDRESS = "Litecoin_click_bot"
# BOT_ADDRESS = "Dogecoin_click_bot"
# BOT_ADDRESS = "BCH_clickbot"
# BOT_ADDRESS = "Zcash_click_bot"
# BOT_ADDRESS = "BitcoinClick_bot"
